version: "3"

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./pokedex/data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: pokedex
      MYSQL_HOST: 172.17.0.1
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8090:8080
    networks:
      - mysql-compose-network

  pokedex:
    container_name: pokedex
    build:
      context: ./pokedex
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pokedex
    depends_on:
      - mysql
    networks:
      - mysql-compose-network
    restart: unless-stopped
      
  world-weather:
    container_name: world-weather
    build:
      context: ./world-weather
    expose:
      - 8081
    ports:
      - 8081:8081
    env_file:
      - ./world-weather/.env

networks: 
  mysql-compose-network:
    driver: bridge